### PR TITLE
Document ignore config parameter

### PR DESCRIPTION
**Pull request by jlambert121**
Updated the readme.  If you want to document it differently, feel free to reject this and reword.

### CODE REVIEW

**Comment by amaltson** [comment]
Sorry, been insanely busy the last couple of days, haven't had a spare minute. I should have some time tomorrow. Sorry for the delay!

**Comment by jlambert121** [comment]
No worries - I always have a backlog of stuff on GH I haven't had time to get to.  Many great contributors, just not enough time.

**Comment by amaltson** [comment]
This LGTM, I do usually write JIRA with all caps. I'll fix it up, pushing out a new version now. Thanks for the contributions.

**Comment by amaltson** [comment]
@jlambert121 version 0.2.2 has been released, thanks for the contributions :smile:

**Pull request merged**
